theme: jekyll-theme-cayman
title: Work Presentation & Document Archive
description: Organizing and presenting business presentations, reports, and technical documentation.

include:
  - "ENP_Expansion_Feedback 2026.pdf"
